services:
  sonar_db:
    image: postgres@sha256:056b54f00419b49289227ab12d09df508543883f407fe9935a2cec430ef8aa8d
    pull_policy: never
    container_name: ${REPO_PREFIX}_sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - sonar_internal
    restart: unless-stopped
  sonarqube:
    image: sonarqube@sha256:24d75d7e0021f2d0f94e4d761b734088b1afc00395d161a7035d61df5a812f5b
    pull_policy: never
    container_name: ${REPO_PREFIX}_sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    networks:
      sonar_internal:
      sonar_scanner:
        aliases:
          - sonarqube
    restart: unless-stopped
networks:
  sonar_internal:
    internal: true
  sonar_scanner:
    name: "${REPO_PREFIX}_sonar_scanner_network"
    driver: bridge
    internal: true
volumes:
  sonar_data:
    name: "${REPO_PREFIX}_sonar_data"
  sonar_extensions:
    name: "${REPO_PREFIX}_sonar_extensions"
  sonar_logs:
    name: "${REPO_PREFIX}_sonar_logs"
  sonar_db_data:
    name: "${REPO_PREFIX}_sonar_db_data"
