package my.portfoliomanager.app.service;

public enum LlmPromptPurpose {
	SAVING_PLAN_NARRATIVE,
	ONE_TIME_NARRATIVE,
	REBALANCER_NARRATIVE,
	KB_BULK_WEBSEARCH,
	KB_DOSSIER_WEBSEARCH,
	KB_DOSSIER_EXTRACTION,
	KB_ALTERNATIVES_WEBSEARCH
}
